from selenium.webdriver.common.by import By


class DailyVitalsPageLocators:
    trash_icon = (By.ID, "del-vitals")
    ok_btn = (By.XPATH, "//div[@class='modal-footer']/a[contains(.,'OK')]")
    select_date_dropdown = (By.ID, "PastDays")
    select_date_dropdown_view = (By.CSS_SELECTOR, "#PastDays option")
    select_date_dropdown_options = (By.CSS_SELECTOR, "#PastDays option")
    date_links = (By.CSS_SELECTOR, ".table-striped td a")
    columns = (By.CSS_SELECTOR, ".table-striped th")
    steps_input_field = (By.ID, "Steps")
    calories_input_field = (By.ID, "Calories")
    weight_input_field = (By.ID, "Weight")
    body_fats_input_field = (By.ID, "BodyFat")
    water_percent_input_field = (By.ID, "WaterPercent")
    muscle_mass_input_field = (By.ID, "MuscleMass")
    resting_hr_input_field = (By.ID, "RestHR")
    hr_variability_input_field = (By.ID, "HRVar")
    sleep_hours_input_field = (By.ID, "SleepHours")
    awake_time_input_field = (By.ID, "AwakeTime")
    sleep_amount_dropdown = (By.ID, "SleepAmount")
    sleep_amount_dropdown_view = (By.CSS_SELECTOR, "#SleepAmount option")
    sleep_amount_dropdown_options = (By.CSS_SELECTOR, "#SleepAmount option")
    sleep_quality_dropdown = (By.ID, "SleepQuality")
    sleep_quality_dropdown_view = (By.CSS_SELECTOR, "#SleepQuality option")
    sleep_quality_dropdown_options = (By.CSS_SELECTOR, "#SleepQuality option")
    stress_amount_dropdown = (By.ID, "Stress")
    stress_amount_dropdown_view = (By.CSS_SELECTOR, "#Stress option")
    stress_amount_dropdown_options = (By.CSS_SELECTOR, "#Stress option")
    blood_pressure_input_field = (By.ID, "Systolic")
    blood_pressure2_input_field = (By.ID, "Diastolic")
    heals_notes_input_field = (By.ID, "HealthNotes")
    submit_add_vitals = (By.ID, "saveButton")
